const filmList = [
  {
    title: "The Shawshank Redemption",
    description:
      "Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.",
    poster: "http://18.231.177.242:3000/image/theshawshankredemption",
    trailer: "http://18.231.177.242:3000/video/theshawshankredemption",
    releaseDate: "1994-09-23",
    rating: 9.3,
    genre: "Drama",
    duration: 142,
    director: "Frank Darabont",
  },
  {
    title: "The Godfather",
    description:
      "The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.",
    poster: "http://18.231.177.242:3000/image/thegodfather",
    trailer: "http://18.231.177.242:3000/video/thegodfather",
    releaseDate: "1972-03-24",
    rating: 9.2,
    genre: "Crime, Drama",
    duration: 175,
    director: "Francis Ford Coppola",
  },
  {
    title: "The Dark Knight",
    description:
      "When the menace known as the Joker emerges from his mysterious past, he wreaks havoc and chaos on the people of Gotham.",
    poster: "http://18.231.177.242:3000/image/thedarkknight",
    trailer: "http://18.231.177.242:3000/video/thedarkknight",
    releaseDate: "2008-07-18",
    rating: 9.0,
    genre: "Action, Crime, Drama",
    duration: 152,
    director: "Christopher Nolan",
  },
  {
    title: "Pulp Fiction",
    description:
      "The lives of two mob hitmen, a boxer, a gangster and his wife intertwine in four tales of violence and redemption.",
    poster: "http://18.231.177.242:3000/image/pulpfiction",
    trailer: "http://18.231.177.242:3000/video/pulpfiction",
    releaseDate: "1994-10-14",
    rating: 8.9,
    genre: "Crime, Drama",
    duration: 154,
    director: "Quentin Tarantino",
  },
  {
    title: "Forrest Gump",
    description:
      "The presidencies of Kennedy and Johnson, the Vietnam War, and more through the eyes of an Alabama man.",
    poster: "http://18.231.177.242:3000/image/forrestgump",
    trailer: "http://18.231.177.242:3000/video/forrestgump",
    releaseDate: "1994-07-06",
    rating: 8.8,
    genre: "Drama, Romance",
    duration: 142,
    director: "Robert Zemeckis",
  },
  {
    title: "Inception",
    description:
      "A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea.",
    poster: "http://18.231.177.242:3000/image/inception",
    trailer: "http://18.231.177.242:3000/video/inception",
    releaseDate: "2010-07-16",
    rating: 8.8,
    genre: "Action, Sci-Fi",
    duration: 148,
    director: "Christopher Nolan",
  },
  {
    title: "Fight Club",
    description:
      "An insomniac office worker and a devil-may-care soapmaker form an underground fight club that evolves into much more.",
    poster: "http://18.231.177.242:3000/image/fightclub",
    trailer: "http://18.231.177.242:3000/video/fightclub",
    releaseDate: "1999-10-15",
    rating: 8.8,
    genre: "Drama",
    duration: 139,
    director: "David Fincher",
  },
  {
    title: "The Matrix",
    description:
      "A computer hacker learns from mysterious rebels about the true nature of his reality and his role in the war against its controllers.",
    poster: "http://18.231.177.242:3000/image/thematrix",
    trailer: "http://18.231.177.242:3000/video/thematrix",
    releaseDate: "1999-03-31",
    rating: 8.7,
    genre: "Action, Sci-Fi",
    duration: 136,
    director: "Lana Wachowski, Lilly Wachowski",
  },
  {
    title: "The Silence of the Lambs",
    description:
      "A young F.B.I. cadet must receive the help of an incarcerated and manipulative cannibal killer to catch another serial killer.",
    poster: "http://18.231.177.242:3000/image/thesilenceofthelambs",
    trailer: "http://18.231.177.242:3000/video/thesilenceofthelambs",
    releaseDate: "1991-02-14",
    rating: 8.6,
    genre: "Crime, Drama, Thriller",
    duration: 118,
    director: "Jonathan Demme",
  },
  {
    title: "Se7en",
    description:
      "Two detectives, a rookie and a veteran, hunt a serial killer who uses the seven deadly sins as his motives.",
    poster: "http://18.231.177.242:3000/image/seven",
    trailer: "http://18.231.177.242:3000/video/seven",
    releaseDate: "1995-09-22",
    rating: 8.6,
    genre: "Crime, Drama, Mystery",
    duration: 127,
    director: "David Fincher",
  },
  {
    title: "Interstellar",
    description:
      "A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival.",
    poster: "http://18.231.177.242:3000/image/interestellar",
    trailer: "http://18.231.177.242:3000/video/interestellar",
    releaseDate: "2014-11-07",
    rating: 8.6,
    genre: "Adventure, Drama, Sci-Fi",
    duration: 169,
    director: "Christopher Nolan",
  },
  {
    title: "The Green Mile",
    description:
      "The lives of guards on Death Row are affected by one of their charges: a black man accused of child murder and rape.",
    poster: "http://18.231.177.242:3000/image/thegreenmile",
    trailer: "http://18.231.177.242:3000/video/thegreenmile",
    releaseDate: "1999-12-10",
    rating: 8.6,
    genre: "Crime, Drama, Fantasy",
    duration: 189,
    director: "Frank Darabont",
  },
  {
    title: "Gladiator",
    description:
      "A former Roman General sets out to exact vengeance against the corrupt emperor who murdered his family.",
    poster: "http://18.231.177.242:3000/image/gladiator",
    trailer: "http://18.231.177.242:3000/video/gladiator",
    releaseDate: "2000-05-05",
    rating: 8.5,
    genre: "Action, Adventure, Drama",
    duration: 155,
    director: "Ridley Scott",
  },
  {
    title: "The Lion King",
    description:
      "A young lion prince flees his kingdom only to learn the true meaning of responsibility and bravery.",
    poster: "http://18.231.177.242:3000/image/thelionking",
    trailer: "http://18.231.177.242:3000/video/thelionking",
    releaseDate: "1994-06-24",
    rating: 8.5,
    genre: "Animation, Adventure, Drama",
    duration: 88,
    director: "Roger Allers, Rob Minkoff",
  },
  {
    title: "The Prestige",
    description:
      "After a tragic accident, two stage magicians engage in a battle to create the ultimate illusion.",
    poster: "http://18.231.177.242:3000/image/theprestige",
    trailer: "http://18.231.177.242:3000/video/theprestige",
    releaseDate: "2006-10-20",
    rating: 8.5,
    genre: "Drama, Mystery, Sci-Fi",
    duration: 130,
    director: "Christopher Nolan",
  },
  {
    title: "The Departed",
    description:
      "An undercover cop and a mole in the police attempt to identify each other while infiltrating an Irish gang.",
    poster: "http://18.231.177.242:3000/image/thedeparted",
    trailer: "http://18.231.177.242:3000/video/thedeparted",
    releaseDate: "2006-10-06",
    rating: 8.5,
    genre: "Crime, Drama, Thriller",
    duration: 151,
    director: "Martin Scorsese",
  },
  {
    title: "Whiplash",
    description:
      "A promising young drummer enrolls at a cut-throat music conservatory where his dreams of greatness are mentored.",
    poster: "http://18.231.177.242:3000/image/whiplash",
    trailer: "http://18.231.177.242:3000/video/whiplash",
    releaseDate: "2014-10-10",
    rating: 8.5,
    genre: "Drama, Music",
    duration: 106,
    director: "Damien Chazelle",
  },
  {
    title: "Saving Private Ryan",
    description:
      "Following the Normandy Landings, a group of U.S. soldiers go behind enemy lines to retrieve a paratrooper.",
    poster: "http://18.231.177.242:3000/image/savingprivateryan",
    trailer: "http://18.231.177.242:3000/video/savingprivateryan",
    releaseDate: "1998-07-24",
    rating: 8.6,
    genre: "Drama, War",
    duration: 169,
    director: "Steven Spielberg",
  },
  {
    title: "Parasite",
    description:
      "Greed and class discrimination threaten the newly formed symbiotic relationship between a wealthy family and the destitute Kim clan.",
    poster: "http://18.231.177.242:3000/image/parasite",
    trailer: "http://18.231.177.242:3000/video/parasite",
    releaseDate: "2019-05-30",
    rating: 8.6,
    genre: "Comedy, Drama, Thriller",
    duration: 132,
    director: "Bong Joon-ho",
  },
  {
    title: "Joker",
    description:
      "In Gotham City, a mentally troubled comedian embarks on a downward spiral of revolution and bloody crime.",
    poster: "http://18.231.177.242:3000/image/joker",
    trailer: "http://18.231.177.242:3000/video/joker",
    releaseDate: "2019-10-04",
    rating: 8.5,
    genre: "Crime, Drama, Thriller",
    duration: 122,
    director: "Todd Phillips",
  },
];

module.exports = filmList;
